apiVersion: v1
kind: Service
metadata:
  labels:
    app: custom-http-backend
  name: custom-http-backend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: custom-http-backend
  sessionAffinity: None
  type: ClusterIP